version: "3.9"

services:
  app:
    build:
      context: .
      target: build
    command: air -d
    volumes:
      - .:/go/app/api
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG_SERVER_PORT}:${DEBUG_SERVER_PORT}
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    container_name: db_postgres
    image: postgres:12
    restart: always
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
