version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    command: air -d
    volumes:
      - .:/opt/app/api
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_SERVER_PORT}:${DEBUG_SERVER_PORT}
    env_file:
      - .env
  postgres:
    container_name: db_postgres
    image: postgres:12
    restart: always
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=hencor
      - POSTGRES_DB=taskgodb
