version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
    ports:
      - "3000:3000"
  postgres:
    container_name: db_postgres
    image: postgres:12
    restart: always
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=hencor
      - POSTGRES_DB=taskgodb
