#!/bin/sh
# TEST_COVERAGE_THRESHOLD=80.0

go test ./... -coverprofile=coverage.out ;\
    if [ $(bc <<< "$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+') < 101.0") -eq 1 ]; then \
        echo "Low test coverage: $(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+') < 101.0" ;\
        # exit 1 ;\
    fi
