#!/bin/sh
TEST_COVERAGE_THRESHOLD=101.0
go test ./... -coverprofile=coverage.out
    coverage=$$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+') ;\
    rm coverage.out ;\
    if [ $$(bc <<< "$$coverage < $(TEST_COVERAGE_THRESHOLD)") -eq 1 ]; then \
        echo "Low test coverage: $$coverage < $(TEST_COVERAGE_THRESHOLD)" ;\
        exit 1 ;\
    fi
