name: Say hello

on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo Sosa se la come
        run: |
          echo "Sosa se la come!"
